var data = {
    cities: [
        {
            name: "Paris",
            city: "Paris",
            countryName: "France",
            latitude: 48.86,
            longitude: 2.3444
        },
        {
            name: "New York",
            city: "New York",
            countryName: "US",
            latitude: 40.667,
            longitude: -73.833
        },
        {
            name: "San Francisco",
            city: "San Francisco",
            countryName: "US",
            latitude: 37.792032,
            longitude: -122.394613
        },
        {
            name: "Roma",
            city: "Roma",
            countryName: "Italia",
            latitude: 41.827637,
            longitude: 12.462732
        },
        {
            name: "Miami",
            city: "Miami",
            countryName: "US",
            latitude: 25.789125,
            longitude: -80.205674
        },
        {
            name: "Tokyo",
            city: "Tokyo",
            countryName: "Japan",
            latitude: 35.687418,
            longitude: 139.692306
        },
        {
            name: "Sydney",
            city: "Sydney",
            countryName: "Australia",
            latitude: -33.917,
            longitude: 151.167
        },
        {
            name: "Ha Noi",
            city: "Ha Noi",
            countryName: "Viet Nam",
            latitude: 21.028511,
            longitude: 105.804817
        },
        {
            name: "Ho Chi Minh",
            city: "Ho Chi Minh",
            countryName: "Viet Nam",
            longitude: 106.660172,
            latitude: 10.762622
        }
    ],
    countries: [
        "AE",
        "AF",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BD",
        "BE",
        "BF",
        "BG",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CU",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "EH",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FR",
        "GA",
        "GB",
        "GE",
        "GH",
        "GL",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IQ",
        "IR",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KO",
        "KP",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MD",
        "ME",
        "MG",
        "MK",
        "ML",
        "MM",
        "MN",
        "MR",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NCY",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PR",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SD",
        "SE",
        "SI",
        "SK",
        "SL",
        "SN",
        "SO",
        "SOL",
        "SR",
        "SS",
        "SV",
        "SY",
        "SZ",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TL",
        "TM",
        "TN",
        "TR",
        "TT",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VE",
        "VN",
        "VU",
        "YE",
        "ZA",
        "ZM",
        "ZW",
    ]
}